### PR TITLE
Fixed PagedLOD Tree structure when exporting VPB datasets and fixed b…

### PR DESCRIPTION
**Pull request by jtorresfabra**
…ase64 textures writting

### CODE REVIEW

**Comment by jtorresfabra** [comment]
Do not merge yet please, I need to rewrite the way the pagedLOD traverses its children, it should be depth first, otherwise memory gets bloated when writing large datasets. I leave the PR opened just in case anybody wants to test it.

**Comment by jtorresfabra** [comment]
It is ready to review now.

**Comment by cedricpinson** [comment]
Seems good to me, did you test with regular files without pagelod node ?

**Comment by jtorresfabra** [comment]
Yes, it works so far.

**Comment by cedricpinson** [comment]
could you rebase on master, master is the main branch. I am deleting develop to avoid confusion

**Comment by jtorresfabra** [comment]
Oops, yes actually I have a patch against master to send to OSG. I'm closing this PR and sending another against master.

**Pull request closed without merging**
