### PR TITLE
sync osganimation with master git 

### PR DESCRIPTION
**Pull request by juval**
In the spirit of closing the gap between your repository and current osg master
 It was Robert that originally charged me (implicitly) of this pull request
 The purpose of this pull request is mainly to sync your changes with
changes in osg requirements that mainly are
 -Callback have changed
 -a lot of tiny changes in order to comply with Coverity scan requirements
But as it has originally cloned from your repo all your changes should be there.
..At the exception of the Keyframe::linearInterpolationDeduplicate() that is not used anywhere

### CODE REVIEW

**Comment by juval** [comment]
So this pull request doesn't contains my hacky fix
The hacky fix was there to take care of the case when an animation change completely  bounds of the rig...
I assume you know the case as you allow user to set its own boundingbox (initialbound)
I resetted the callback in order the bounds to be computed based on the first transformed vertices...but it's not general purpose so i'd rather remove it.

**Comment by mp3butcher** [comment]
And to answer Cédric about Robert ability to process PL, I think he's ready...at least technically...But it'll have to stay incremental and well targeted. To speak of myself I prefer to keep pushing zip on the mailing list, in order not to "overbrain" him

**Comment by marchelbling** [comment]
@juval , `Keyframe::linearInterpolationDeduplicate()` is used in the [`AnimationCleanerVisitor`](https://github.com/cedricpinson/osg/blob/master/src/osgPlugins/gles/AnimationCleanerVisitor#L439)  from the gles plugin.
This is used as a way to remove unnecessary data when using animation baking (for which we need also to push some code back in Robert repo).
If you could just let this function I'd run our test suite against your PR.

**Comment by juval** [comment]
done

**Comment by marchelbling** [comment]
@juval thanks. It will actually require more time than I expected as it doesn't merge in our (sketchfab) repo so I'll need to update before being able to test your changes.

**Pull request closed without merging**
