### PR TITLE
Animation update

### PR DESCRIPTION
**Pull request by marchelbling**
Hey @jtorresfabra you may want to have a look at this (rather big) PR. I rewrote some of your changes in `gles/GeometrySplitterVisitor` a bit differently but have no models to test that it still works the way you expect. 

Most of these changes are related to animation. Most gles visitors were impacted because we need to carefully handle MorphGeometry (with the case where it's a RigGeometry source). Hopefully we break nothing (at least in our own tests). Note that there is a `glesMode=(all|animation|geometry)` flag in gles to consider animation or geometry solely or both (default).

Some of these changes will have to be ported to the main trunk (especially I modified some "low level" classes like `osg::Quat`, `osgAnimation::Channel`, added `osg::QuatArray`etc.).

:christmas_tree:

### CODE REVIEW

**Comment by jtorresfabra** [comment]
Hey @marchelbling !

Thanks for the advice... I'm afraid now I don't have so much time to test, just returned from a trip and have tons of work waiting me. :sweat: Anyway, I'll try to do my best and test it asap. 

 About the gles/GeometrySplitterVisitor what I made was in order to support serialization of osg::Text. I was talking with @cedricpinson to not export Texts by default, as probably you don't need it for Sketchfab, that's the reasonn why it was enabled using an option ( "exportNonGeometryDrawables" ) . So I'm unsure about that point of the PR (I think it will export always texts currently, isn't it?). Anyway I will give a try. 

Other point I talked with Cedric was about doing some cleaning in the headers of gles/osgjs plugins. Adding new headers to CMakeLists.txt in core libraries is a must, because CMake install that files in the distribution only if they are stated in the CMakeLists.txt file. In osgPlugins is not a must but it helps to show files when creating IDE projects ( for qtcreator, Visual Studio, etc..). In a quick review I see now at least  src/osgPlugins/gles/debug is not added to CMakeLists.txt. 

Also I recall the duplicity of at least TriangleLinePointIndexFunctor, as it is now in the core of OSG, we don't need to have it in the plugins anymore, I sent two patches some time ago to fix issues also in OSG core (adding it to the distribution and adding it to the osg namespace ). I think onme was merged, I will check the status of the other one.  

A pointer to the unnecesary file:
https://github.com/marchelbling/osg/blob/animation_update/src/osgPlugins/gles/TriangleLinePointIndexFunctor

I also was wondering if you explored the serialization support using stream operators for osgjs. 

Last but not least I want to say that you are doing a great job guys :). Keep up rocking! :+1: .

**Comment by marchelbling** [comment]
hey @jtorresfabra, no rush here!

Regarding the `exportNonGeometryDrawables`, I kept the option still set to false by default.
You are correct that the behavior in my PR is to keep *all* non-geometry drawables (as implied by the option name) and it does not explicitely check wether it's text or something else.
Where do you think it could break? The 'philosophy' I have in mind is that in the end, unsupported objects will not be serialized in the osgjs output so that should not be an issue.

You are completely right regarding the CMakeList. I fixed it and removed `TriangleLinePointIndexor` from gles.

I did not yet investigate much time on rewriting osgjs serialization. That would definitively be something to do but that would be a huge refactoring so probably not going to happen very soon (unless you started something that we could build upon?)

**Comment by jtorresfabra** [comment]
> Regarding the exportNonGeometryDrawables, I kept the option still set to false by default.

Ok I just realized about https://github.com/marchelbling/osg/blob/animation_update/src/osgPlugins/gles/GeometrySplitterVisitor#L384 ... didn't see it before :+1: 

> Where do you think it could break? The 'philosophy' I have in mind is that in the end, unsupported objects will not be serialized in the osgjs output so that should not be an issue.

Take a look to the hierarchy at http://trac.openscenegraph.org/documentation/OpenSceneGraphReferenceDocs/a00222.html. 
I agree with that philosophy, the only thing is to check that it does not fail.

> I did not yet investigate much time on rewriting osgjs serialization. That would definitively be something to do but that would be a huge refactoring so probably not going to happen very soon (unless you started something that we could build upon?)

Oh, I afraid I didn't. The refactor would be a pain of course, but it could have great benefits ( for example convert from osgjs to other osg formats easily). Anwyay I was only wondering if you have thought about it. We can discuss about it in the future of course. 

Okay, I will test with some texts to see if everything works as expected and I'll ping you back. Thanks!

**Comment by jtorresfabra** [comment]
Hi @marchelbling 
I'm just starting to test this PR. CMake fails because https://github.com/marchelbling/osg/blob/animation_update/src/osgPlugins/gles/CMakeLists.txt#L37 doesn't exist. That line should be removed ;).

I'll ping you with my test results.

**Comment by jtorresfabra** [comment]
@marchelbling also I'm getting compilation errors here https://github.com/marchelbling/osg/blob/animation_update/src/osgPlugins/gles/TriangleStripVisitor.cpp#L9, as it seems you forget to add code to osgUtil::TriStrip visitor, could it be?

I have some more errors, I'll be pointing them here.

**Comment by marchelbling** [comment]
@jtorresfabra sorry for this mess. It should now be fixed:

* CMakeList updated (again...juggling with 3 repos is error prone)
* added our update to `osgUtil::TriStripVisitor` (basically as gles as its own mesh indexor, we don't want the stripper to re-index meshes)
* added some fixes in the animation code
* added a full rewrite of geometry splitting (removed the need for an external "forsyth post transform" code); do you use this visitor much?

I checked that this compiles correctly on ubuntu. Let me know if you still have compilation/execution issues!

**Comment by jtorresfabra** [comment]
Thanks @marchelbling . Sorry about that but I'm still getting errors...  Probably related to my compiler (C++ 4.9). So I'm getting errors in https://github.com/marchelbling/osg/blob/animation_update/include/osgAnimation/Keyframe#L117, it's weird because if I change to this->swap( deduplicated) it works. 

Anyway I would like to do some comments in this class:
- Inheriting from std::vector is not a good idea because it could introduce undefined behaviour through violation of virtual destructor rules. That's the reason why osg::MixinVector was created, so IMO you should use osg:MixinVector to inherit from. 
- The classes in that file are missing virtual destructors ( important if any time you want to inherit from that class ) For example https://github.com/marchelbling/osg/blob/animation_update/include/osgAnimation/Keyframe#L72
Also KeyFrame misses a destructor.

For the swap weird error I don't have answer yet. It seems it is waiting for two parameters, but I didn't see any using std::vector in the class, so no clue at the moment.

**Comment by marchelbling** [comment]
@jtorresfabra we're still using gcc 4.6 indeed. Not clear why it would fail with 4.9 (as it seems that it is still not using C++11 by default; however, I've only been reading bad things about 4.9).

Regarding your remarks (note that the code is already in the OSG/osgAnimation trunk):

* I think relying on the default destructor is safe for the osgAnimation classes that do not declare it explicitely
* `KeyframeContainer` inherits from `osg::Referenced` that declares a virtual destructor so `~KeyframeContainer` *is* virtual
* as `TemplateKeyframeContainer` is also inheriting from `KeyframeContainer` which has a virtual desctrutor through `osg::Referenced`, so I *think* it makes  `TemplateKeyframeContainer` destructor virtual too

I quickly tried to replace the `std::vector` inheritance by `osg::MixinVector` and it leads to other errors that I'd rather not dig now.
I do not understand the reason of the compiler error for the `swap` call but I don't mind making it explicit. Out of curiosity, could you paste the compiler error for this?  

I've been wondering if the animation code should go in the gles plugin. Do you intend to use animation at all? If not maybe the solution to make everyone happy would be to separate the animation code from the gles plugin.

**Comment by jtorresfabra** [comment]
> @jtorresfabra we're still using gcc 4.6 indeed. Not clear why it would fail with 4.9 (as it seems that it is still not using C++11 by default; however, I've only been reading bad things about 4.9).

It's the default compiler in Ubuntu 15.04. Not my choice :wink: .

> KeyframeContainer inherits from osg::Referenced that declares a virtual destructor so ~KeyframeContainer is virtual

Oh didn't notice that. Anyway declaring it doesn't hurt and you don't have to go upon the inheritance graph to find destructors. It's the coding style we use, but it's ok! Sorry for that noise. 

> I quickly tried to replace the std::vector inheritance by osg::MixinVector and it leads to other errors that I'd rather not dig now.

Weird, I did not get any errors replacing std::vector for osg::MixinVector in that class. Also I'm quite in the opinion that this is the way to go, rather than inheriting from std::vector.  

> I do not understand the reason of the compiler error for the swap call but I don't mind making it explicit. Out of curiosity, could you paste the compiler error for this?

Sure:
n file included from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Sampler:26:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Channel:23,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/AnimationUpdateCallback:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateMatrixTransform:21,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateBone:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:11:
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Keyframe: In instantiation of 'unsigned int osgAnimation::TemplateKeyframeContainer<T>::linearInterpolationDeduplicate() [with T = osg::Quat]':
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:389:1:   required from here
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Keyframe:119:34: error: no matching function for call to 'swap(osgAnimation::TemplateKeyframeContainer<osg::Quat>::VectorType&)'
                 swap(deduplicated);
                                  ^
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Keyframe:119:34: note: candidates are:
In file included from /usr/include/c++/4.9/deque:64:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgDB/ReaderWriter:24,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgDB/Registry:24,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgDB/FileUtils:17,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:6:
/usr/include/c++/4.9/bits/stl_deque.h:2083:5: note: template<class _Tp, class _Alloc> void std::swap(std::deque<_Tp, _Alloc>&, std::deque<_Tp, _Alloc>&)
     swap(deque<_Tp,_Alloc>& __x, deque<_Tp,_Alloc>& __y)
     ^
/usr/include/c++/4.9/bits/stl_deque.h:2083:5: note:   template argument deduction/substitution failed:
In file included from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Sampler:26:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Channel:23,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/AnimationUpdateCallback:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateMatrixTransform:21,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateBone:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:11:
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Keyframe:119:34: note:   'osgAnimation::TemplateKeyframeContainer<osg::Quat>::VectorType {aka std::vector<osgAnimation::TemplateKeyframe<osg::Quat>, std::allocator<osgAnimation::TemplateKeyframe<osg::Quat> > >}' is not derived from 'std::deque<_Tp, _Alloc>'
                 swap(deduplicated);
                                  ^
In file included from /usr/include/c++/4.9/set:62:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Shader:29,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/StateAttribute:20,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/StateSet:18,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/State:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/RenderInfo:17,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Drawable:21,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Geometry:17,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:2:
/usr/include/c++/4.9/bits/stl_multiset.h:829:5: note: template<class _Key, class _Compare, class _Alloc> void std::swap(std::multiset<_Key, _Compare, _Alloc>&, std::multiset<_Key, _Compare, _Alloc>&)
     swap(multiset<_Key, _Compare, _Alloc>& __x,
     ^
/usr/include/c++/4.9/bits/stl_multiset.h:829:5: note:   template argument deduction/substitution failed:
In file included from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Sampler:26:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Channel:23,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/AnimationUpdateCallback:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateMatrixTransform:21,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateBone:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:11:
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Keyframe:119:34: note:   'osgAnimation::TemplateKeyframeContainer<osg::Quat>::VectorType {aka std::vector<osgAnimation::TemplateKeyframe<osg::Quat>, std::allocator<osgAnimation::TemplateKeyframe<osg::Quat> > >}' is not derived from 'std::multiset<_Key, _Compare, _Alloc>'
                 swap(deduplicated);
                                  ^
In file included from /usr/include/c++/4.9/set:61:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Shader:29,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/StateAttribute:20,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/StateSet:18,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/State:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/RenderInfo:17,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Drawable:21,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Geometry:17,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:2:
/usr/include/c++/4.9/bits/stl_set.h:845:5: note: template<class _Key, class _Compare, class _Alloc> void std::swap(std::set<_Key, _Compare, _Alloc>&, std::set<_Key, _Compare, _Alloc>&)
     swap(set<_Key, _Compare, _Alloc>& __x, set<_Key, _Compare, _Alloc>& __y)
     ^
/usr/include/c++/4.9/bits/stl_set.h:845:5: note:   template argument deduction/substitution failed:
In file included from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Sampler:26:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Channel:23,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/AnimationUpdateCallback:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateMatrixTransform:21,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateBone:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:11:
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Keyframe:119:34: note:   'osgAnimation::TemplateKeyframeContainer<osg::Quat>::VectorType {aka std::vector<osgAnimation::TemplateKeyframe<osg::Quat>, std::allocator<osgAnimation::TemplateKeyframe<osg::Quat> > >}' is not derived from 'std::set<_Key, _Compare, _Alloc>'
                 swap(deduplicated);
                                  ^
In file included from /usr/include/c++/4.9/map:62:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/BufferObject:26,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Array:47,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Shape:21,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Drawable:18,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Geometry:17,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:2:
/usr/include/c++/4.9/bits/stl_multimap.h:955:5: note: template<class _Key, class _Tp, class _Compare, class _Alloc> void std::swap(std::multimap<_Key, _Tp, _Compare, _Alloc>&, std::multimap<_Key, _Tp, _Compare, _Alloc>&)
     swap(multimap<_Key, _Tp, _Compare, _Alloc>& __x,
     ^
/usr/include/c++/4.9/bits/stl_multimap.h:955:5: note:   template argument deduction/substitution failed:
In file included from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Sampler:26:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Channel:23,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/AnimationUpdateCallback:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateMatrixTransform:21,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/UpdateBone:19,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:11:
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Keyframe:119:34: note:   'osgAnimation::TemplateKeyframeContainer<osg::Quat>::VectorType {aka std::vector<osgAnimation::TemplateKeyframe<osg::Quat>, std::allocator<osgAnimation::TemplateKeyframe<osg::Quat> > >}' is not derived from 'std::multimap<_Key, _Tp, _Compare, _Alloc>'
                 swap(deduplicated);
                                  ^
In file included from /usr/include/c++/4.9/map:61:0,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/BufferObject:26,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Array:47,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Shape:21,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Drawable:18,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osg/Geometry:17,
                 from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:2:
/usr/include/c++/4.9/bits/stl_map.h:1052:5: note: template<class _Key, class _Tp, class _Compare, class _Alloc> void std::swap(std::map<_Key, _Tp, _Compare, _Alloc>&, std::map<_Key, _Tp, _Compare, _Alloc>&)
     swap(map<_Key, _Tp, _Compare, _Alloc>& __x,
     ^
/usr/include/c++/4.9/bits/stl_map.h:1052:5: note:   template argument deduction/substitution failed:

and so on...

> I've been wondering if the animation code should go in the gles plugin. Do you intend to use animation at all? If not maybe the solution to make everyone happy would be to separate the animation code from the gles plugin.

I don't use it right now but maybe in the future I will. What are you thinking about?

**Comment by marchelbling** [comment]
> It's the default compiler in Ubuntu 15.04. Not my choice :wink: .

I see, not far away from 16.04 :)

> Oh didn't notice that. Anyway declaring it doesn't hurt and you don't have to go upon the inheritance graph to find destructors. It's the coding style we use, but it's ok! Sorry for that noise.

Agree it's way more readable to repeat the `virtual` keyword. I however tend to avoid modifying not required code in osg core as it's currently a bit paintful to push changes back to the main repo (I still have a lot of small changes to report). 

> Weird, I did not get any errors replacing std::vector for osg::MixinVector in that class. Also I'm quite in the opinion that this is the way to go, rather than inheriting from std::vector.

Well I first forgot to include `osg/MixinVector` but now I have errors in some plugins (probably within the changes that we made and did not push yet to the main repo).

> Sure:
> ```
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation> /Keyframe:119:34: error: no matching function for call to 'swap(osgAnimation::TemplateKeyframeContainerosg::Quat::VectorType&)'
swap(deduplicated);
^
/home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgAnimation/Keyframe:119:34: note: candidates are:
In file included from /usr/include/c++/4.9/deque:64:0,
from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgDB/ReaderWriter:24,
from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgDB/Registry:24,
from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/include/osgDB/FileUtils:17,
from /home/jtorres/Projects/OpenSceneGraph/OpenSceneGraph-JS-fork/src/osgPlugins/bvh/ReaderWriterBVH.cpp:6:
/usr/include/c++/4.9/bits/stl_deque.h:2083:5: note: template void std::swap(std::deque<_Tp, _Alloc>&, > std::deque<_Tp, _Alloc>&)
swap(deque<_Tp,_Alloc>& __x, deque<_Tp,_Alloc>& __y)
 ^
 ...
```
> and so on...

That looks strange indeed. I pushed the change with explicit `this->swap` so should be fine now.
(just wondering if explicitely including `<vector>` could fix this)

> I don't use it right now but maybe in the future I will. What are you thinking about?

Before we released animation support in sketchfab, gles was only processing geometry. We added animation processing in the plugin but it feels like it's doing too much (namely, we are not using both animation and geometry processing at the same time in our pipeline) so maybe just removing animation processing and putting it in an other plugin would be better, especially since animation processing is not completely related to opengles.

**Comment by jtorresfabra** [comment]
> Well I first forgot to include osg/MixinVector but now I have errors in some plugins (probably within the changes that we made and did not push yet to the main repo).

Humm I just replaced the std::vector ocurrences by osg::MixinVector in KeyFrame in your branch (I just cloned it) and it compiles without problem. I don't know what could be happening. 

> That looks strange indeed. I pushed the change with explicit this->swap so should be fine now.
> (just wondering if explicitely including <vector> could fix this)

Just tried and... nope, it does not do the trick. Anyway if you do a quick search about inheriting from std::vector it will explain better than me why not to do it :smile: 

> just removing animation processing and putting it in an other plugin would be better, especially since animation processing is not completely related to opengles.

Totally agree then, at least with the part that is not related with gles.

Thanks for your patience :)

**Comment by marchelbling** [comment]
@jtorresfabra sorry for the long silence. I just updated my PR and changed the `TemplateKeyframeContainer` inheritance (the compilation issues were actually in changes we made and that I did not pushed back yet).
I cleaned a bit the osgjs serialization code and added a fix for animation cleaning.
Hopefully this will now be all good for you. I'll plan some time soon to push our changes to the main trunk.

**Comment by jtorresfabra** [comment]
@marchelbling thanks for your work, I'm sorry to be a pain the neck :). I'm gonna test the changes right now and let you know about the results.

**Comment by jtorresfabra** [comment]
@marchelbling @cedricpinson All seems to work ok as far as I tested :+1: 
Green light from me!

**Comment by marchelbling** [comment]
@jtorresfabra great!
Btw, you're not a pain. We need to improve the overall workflow to make updates less painful

**Comment by marchelbling** [comment]
@jtorresfabra I just added one last small change: I moved "utf8 string" specific code from `json_stream` to `utf8_string` (and updated the CMakeLists.txt :)).

@cedricpinson should be good to be merged!

**Comment by jtorresfabra** [comment]
@marchelbling great, all is ok from me. Go ahead!

**Pull request merged**
