### PR TITLE
sync osganimation with master git

### PR DESCRIPTION
**Pull request by juval**
In the spirit of closing the gap between your repository and current osg master
-cloned for your repo
-updated and corrected for osg master (mainly coverity warning fixes)
-pushed to osg master
A fix has also been apply in RigGeometry in order correct bounds to be computed as the computeboundcallback can be called before the update callback:
 compute bound callback setup has been displaced from constructor to computeMatrixFromRootSkeleton() .
It would be great you validate it on osg forum:
http://forum.openscenegraph.org/viewtopic.php?p=67822#67822

### CODE REVIEW

**Comment by mp3butcher** [comment]
The fix applied in RigGeometry is very hacky..I will try to dig out better the encountered bug

**Comment by cedricpinson** [comment]
Could you give a bit more context ? what bug/fix we are talking about.
More generally if now robert process PR I could report all change we made in my repo directly on official osg.

**Comment by mp3butcher** [comment]
A strange bug encountered by a osg user
http://forum.openscenegraph.org/viewtopic.php?t=15933
I began to dive in osganimation code but still haven't spot the real problem

**Comment by mp3butcher** [comment]
The purpose of this pull request is mainly to sync your changes with changes osg requirements that mainly are
-Callback have changed
-a lot of tiny changes in order to comply with Coverity scan requirements
It was Robert that originally charge me (implicitly) of this pull request (I create 2 git account to have 2 osg forks master and yours)
I will remove the hacky fix and publish a new pull request

**Comment by jtorresfabra** [comment]
Hi Julien,

El 26/6/2016 5:35 p. m., "Julien Valentin" <notifications@github.com>
escribió:
>
> The purpose of this pull request is mainly to sync your changes with
changes osg requirements that mainly are
> -Callback have changed
> -a lot of tiny changes in order to comply with Coverity scan requirements
> It was Robert that originally charge me (implicitly) of this pull request
(I create 2 git account to have 2 osg forks master and yours)

Don't want to add noise but:
You can have different remotes in the same repository and switch between
branches, that's how it works.

Cheers.

**Comment by juval** [comment]
Oh I didn't know that

**Pull request closed without merging**
